### ISSUE TITLE
CI failing on main branch due to i18n

### ISSUE THREAD

**Issue by tkroening** [CMU-313/spring24-nodebb-roger#31]
@choksis8168  CI is failing on `main` with this error message:
```
1) "en-US" file contents
       should contain every translation key contained in its source counterpart:

      AssertionError [ERR_ASSERTION]: Extra keys found in namespace topic for language "en-US"
      + expected - actual

      -186
      +187
```
Maybe the extra key added to `en-US` needs to be reflected somewhere else also? I've made a PR (#30) that might get us started on fixing this.

**Comment by tkroening** [comment]
@choksis8168 It seems like NodeBB actually wants a translation for every language:
```
  3006 passing (4m)
  1 failing
  1) "ar" file contents
       should contain every translation key contained in its source counterpart:
      AssertionError [ERR_ASSERTION]: topic:resolve missing in ar
      + expected - actual
      -false
      +true
      
      at /home/runner/work/spring24-nodebb-roger/spring24-nodebb-roger/test/i18n.js:111:29
      at Array.forEach (<anonymous>)
      at /home/runner/work/spring24-nodebb-roger/spring24-nodebb-roger/test/i18n.js:110:36
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/i18n.js:105:31)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:128:17)
```

I think we'll either need to paste the English string into every file or abandon `i18n` for this feature.

**Comment by tkroening** [comment]
See Chenjia's PR (#21) for how to do Option 1.

**Comment by choksis8168** [comment]
Will take a look at right now! Planning on making changes to the topics.json files like Chenjia did.
